### ISSUE TITLE
PTP peice size limitations

### ISSUE THREAD

**Issue by BoBeR182** [Audionut/Upload-Assistant#136]
```
Traceback (most recent call last):
  File "/home/bober/Upload-Assistant/upload.py", line 810, in do_the_thing
    await ptp.upload(meta, ptpUrl, ptpData, disctype)
  File "/home/bober/Upload-Assistant/src/trackers/PTP.py", line 1038, in upload
    raise UploadException(f"Upload to PTP failed: {errorMessage} ({response.status_code}). (We are still on the upload page.)")  # noqa F405
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src.exceptions.UploadException: Upload to PTP failed: <div>The piece size of 16 MiB (2^24 ~156 pieces) is not within limits. It must be 1 MiB (2^20 ~2487 pieces) to 8 MiB (2^23 ~311 pieces)<br />You can view the piece size chart here: <a href='upload.php?action=piecesize'>Piece Size Chart</a> (200). (We are still on the upload page.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bober/Upload-Assistant/upload.py", line 987, in <module>
    asyncio.run(do_the_thing(base_dir))  # Pass the correct base_dir value here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/bober/Upload-Assistant/upload.py", line 814, in do_the_thing
    console.print(traceback.print_exc())
                  ^^^^^^^^^
UnboundLocalError: cannot access local variable 'traceback' where it is not associated with a value
```

**Comment by Audionut** [comment]
Torf does not have a function that returns the number of pieces, which means it would be all guesstimation to determine whether or not the torrent is within the piece size (actually number of pieces) requirement.

I do a whole bunch of dicky math in [prep.py when doing torrent file creation](https://github.com/Audionut/Upload-Assistant/blob/ce2395a22ecb10bf7fffa831a3373ca389fb1604/src/prep.py#L2636), but I'm not going to duplicate that code in ptp.py because of a bad input. Better to regenerate the torrent file and populate trackers with less retarded torrent files.
