### ISSUE TITLE
HUNO BD crash

### ISSUE THREAD

**Issue by azulu** [Audionut/Upload-Assistant#143]
When uploading a BD to HUNO, the below error occurs, during determining the release type:
```
Traceback (most recent call last):
  File "Upload-Assistant/upload.py", line 985, in <module>
    asyncio.run(do_the_thing(base_dir))  # Pass the correct base_dir value here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "Upload-Assistant/upload.py", line 622, in do_the_thing
    dupes = await tracker_class.search_existing(meta, disctype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Upload-Assistant/src/trackers/HUNO.py", line 286, in search_existing
    'types[]': await self.get_type_id(meta),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Upload-Assistant/src/trackers/HUNO.py", line 238, in get_type_id
    video_encode = meta['video_encode']
                   ~~~~^^^^^^^^^^^^^^^^
KeyError: 'video_encode'
```

If we ignore the line about encodes (238), it fails when looking for the MediaInfo file:

```
Traceback (most recent call last):
  File "Upload-Assistant/upload.py", line 985, in <module>
    asyncio.run(do_the_thing(base_dir))  # Pass the correct base_dir value here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "Upload-Assistant/upload.py", line 629, in do_the_thing
    await tracker_class.upload(meta, disctype)
  File "Upload-Assistant/src/trackers/HUNO.py", line 55, in upload
    'name': await self.get_name(meta),
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Upload-Assistant/src/trackers/HUNO.py", line 157, in get_name
    audio = self.get_audio(meta)
            ^^^^^^^^^^^^^^^^^^^^
  File "Upload-Assistant/src/trackers/HUNO.py", line 119, in get_audio
    with open(media_info_path, 'r', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Upload-Assistant/tmp/FILM/MEDIAINFO.txt'
```

Unsure how to approach it.

It might be fallout from my "web type fix" #76 which concerns the aforementioned line 238. Don't know why it would impact BDs though.

No such problems with other trackers.

**Comment by Audionut** [comment]
And there's clearly no mediainfo with bluray. Not sure what the site expects, but ANT and I think the other unit3d site files will have hints how to handle that.
