### ISSUE TITLE
Upload fail for HUNO

### ISSUE THREAD

**Issue by ykmtail** [Audionut/Upload-Assistant#146]
Failing with
```
Traceback (most recent call last):
  File "/Upload-Assistant/upload.py", line 985, in <module>
    asyncio.run(do_the_thing(base_dir))  # Pass the correct base_dir value here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Upload-Assistant/upload.py", line 629, in do_the_thing
    await tracker_class.upload(meta, disctype)
  File "/Upload-Assistant/src/trackers/HUNO.py", line 55, in upload
    'name': await self.get_name(meta),
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Upload-Assistant/src/trackers/HUNO.py", line 227, in get_name
    return ' '.join(name.split()).replace(": ", " - ")
                    ^^^^
UnboundLocalError: cannot access local variable 'name' where it is not associated with a value
```
Mediainfo
```
General
Unique ID                                : abc
Complete name                            :Mov.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 6.37 GiB
Duration                                 : 2 h 27 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 6 167 kb/s
Movie name                               : Mov
Encoded date                             : UTC 2024-11-23 13:57:04
Writing application                      : mkvmerge v79.0 ('Funeral Pyres') 64-bit
Writing library                          : libebml v1.4.4 + libmatroska v1.7.1

Video
ID                                       : 1
ID in the original source medium         : 224 (0xE0)
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@Main
Format settings                          : CustomMatrix / BVOP
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : M=3, N=15
Format settings, picture structure       : Frame
Codec ID                                 : V_MPEG2
Codec ID/Info                            : MPEG 1 or 2 Video
Duration                                 : 2 h 27 min
Bit rate mode                            : Variable
Bit rate                                 : 5 407 kb/s
Maximum bit rate                         : 8 000 kb/s
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 24.087 FPS
Original frame rate                      : 29.970 (30000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.649
Time code of first frame                 : 00:00:00:01
Time code source                         : Group of pictures header
GOP, Open/Closed                         : Closed
Stream size                              : 5.58 GiB (88%)
Language                                 : Telugu
Default                                  : Yes
Forced                                   : No
Original source medium                   : DVD-Video

Audio
ID                                       : 2
ID in the original source medium         : 189 (0xBD)137 (0x89)
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 2 h 27 min
Bit rate mode                            : Constant
Bit rate                                 : 754 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Delay relative to video                  : 3 s 437 ms
Stream size                              : 797 MiB (12%)
Title                                    : DTS (Digital Theater Systems)
Language                                 : Telugu
Default                                  : Yes
Forced                                   : No
Original source medium                   : DVD-Video

Text #1
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 2 h 23 min
Bit rate                                 : 67 b/s
Count of elements                        : 2065
Stream size                              : 70.8 KiB (0%)
Title                                    : BF1337
Language                                 : English
Default                                  : Yes
Forced                                   : No

Text #2
ID                                       : 4
ID in the original source medium         : 189 (0xBD)32 (0x20)
Format                                   : VobSub
Muxing mode                              : zlib
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : Picture based subtitle format used on DVDs
Duration                                 : 2 h 23 min
Bit rate                                 : 5 227 b/s
Count of elements                        : 2093
Stream size                              : 5.37 MiB (0%)
Title                                    : ESub
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : DVD-Video
```

Also some files like the above are not being detected as NTSC

**Comment by Audionut** [comment]
DVD remux?

Probably same fix as in main code https://github.com/Audionut/Upload-Assistant/commit/dee0167103efd356a4df076653e7da75b30d1971

**Comment by ykmtail** [comment]
Yes, using the latest docker image, yet getting the issue.
Also, btw I took to pull now and tried to run,
```
Traceback (most recent call last):
  File "/Upload-Assistant/src/prep.py", line 21, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
None
Missing Module Found. Please reinstall required dependancies.
pip3 install --user -U -r requirements.txt

**Comment by Audionut** [comment]
Hmm, strange I didn't need to install locally. Added to requirements, thanks.

Also pushed that HUNO fix, should work.

**Comment by ykmtail** [comment]
Grabbed the latest master image, still the issue persists.
Should I wait for sometime for changes to reflect in image?

**Comment by Audionut** [comment]
Which issue exactly? For tqdm, running the requirements.txt should work, been confirmed elsewhere, although I'm not sure they're on docker.

**Comment by ykmtail** [comment]
I was referring to HUNO issue

**Comment by ykmtail** [comment]
I've sent a PM there

**Comment by Audionut** [comment]
Gosh, I didn't even look at the movie naming section, because it was fine in the main code.
