### ISSUE TITLE
infinite loop on DVD-R preparing stage screenshots

### ISSUE THREAD

**Issue by BoBeR182** [Audionut/Upload-Assistant#181]
When trying to parse a DVD-R, for upload it hangs indefinitely on the `Saving Screens... 0/7` stage.
```
No metadata file found at /home/bober/Upload-Assistant/tmp/MOVIENAME.NTSC.DVD9.MPEG-2.DD2.0-MW/meta.json
Gathering info for MOVIENAME.NTSC.DVD9.MPEG-2.DD2.0-MW
ID: MOVIENAME.NTSC.DVD9.MPEG-2.DD2.0-MW
SRRDB: No match found
Searching PTP for: MOVIENAME.NTSC.DVD9.MPEG-2.DD2.0-MW
Could not find any release matching MOVIENAME.NTSC.DVD9.MPEG-2.DD2.0-MW on PTP
Skipping PTP as no match found
No ID found in meta for HDB, searching by file name
Error: File not found at /home/bober/Upload-Assistant/tmp/MOVIENAME.NTSC.DVD9.MPEG-2.DD2.0-MW/BD_SUMMARY_00.txt
No matches found on any trackers.
Saving Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/7 -:--:--Analyzing VOB file: 01_1.VOB
Track 0: Duration=4869.184, Width=None, Height=None
Track 0: Duration=0.033, Width=720, Height=480
Valid track found: voblength=0.033, n=0
Saving Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/7 -:--:--^CProgram interrupted. Exiting.
Saving Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/7 -:--:--^CException ignored in atexit callback: <function _exit_function at 0x768d95d37600>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/util.py", line 360, in _exit_function
    p.join()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt: 
Saving Screens... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/7 -:--:--
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bober/Upload-Assistant/src/prep.py", line 1418, in dvd_screenshots
    ss_times = self.valid_ss_time(ss_times, num_screens + 1, voblength)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bober/Upload-Assistant/src/prep.py", line 1648, in valid_ss_time
    sst = random.randint(round(length / 5), round(4 * length / 5))  # Adjust range for more spread out times
                         ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt
```

**Comment by BoBeR182** [comment]
Confirming fixed screenshot capture on `development` branch working.
