### ISSUE TITLE
Season folder processing failure

### ISSUE THREAD

**Issue by deitybob12** [Audionut/Upload-Assistant#185]
I just used upload.py (after updating to latest version) for Killer.Cases.S02.1080p.WEB-DL.AAC2.0.H.264-squalor and  Killer.Cases.S04.1080p.WEB.h264-EDITH without issue. But when attempting the same with Killer.Cases.S01.1080p.WEB-DL.AAC2.0.H.264-squalor I get a script failure (see below).  Here is my command, the initial processing steps were I answered Y then Enter (to accept as is), then issues related to screenshots then CRITICAL failure. Do you need a debugging output or other info to troubleshoot?

$ upload.py Killer.Cases.S01.1080p.WEB-DL.AAC2.0.H.264-squalor/
Gathering info for Killer.Cases.S01.1080p.WEB-DL.AAC2.0.H.264-squalor
SRRDB: No match found
No ID found in meta for AITHER, searching by file name
Searching AITHER by file name: Killer.Cases.S01E01.The.Doctor.is.Dead.1080p.WEB-DL.AAC2.0.H.264-squalor.mkv
Found the following IDs on Tracker:
TMDb ID: 114635
TVDb ID: 392853
Filename: Killer.Cases.S01E01.The.Doctor.is.Dead.1080p.WEB-DL.AAC2.0.H.264-squalor.mkv
Do you want to use these IDs from Tracker? (Y/n): y
Successfully grabbed description from AITHER
Extracted description: [center]
[/center]
Do you want to edit, discard or keep the description?
Enter 'e' to edit, 'd' to discard, or press Enter to keep it as is:
Keeping the original description.
Valid data found on AITHER, setting meta values
Image verified successfully: https://images2.imgbox.com/66/19/JwhqBBck_o.png
Image https://images2.imgbox.com/66/19/JwhqBBck_o.png resolution (170p) is outside the allowed range (756-1080p). Skipping.
Failed to retrieve image: https://iili.io/02Kg6X.md.png (status code: 404)
Failed to retrieve image: https://iili.io/02K4Fn.md.png (status code: 404)
Failed to retrieve image: https://iili.io/02KSnI.md.png (status code: 404)
Failed to retrieve image: https://iili.io/02KvZN.md.png (status code: 404)
Failed to retrieve image: https://iili.io/02K6as.md.png (status code: 404)
Failed to retrieve image: https://iili.io/02KP8G.md.png (status code: 404)
AITHER data successfully updated in meta
Match found on tracker: AITHER
All screenshots already exist. Skipping capture process.
Successfully captured 0 screenshots.
2024-12-10 04:06:24,529 CRITICAL [imdbpy] /home/user/.local/lib/python3.12/site-packages/imdb/_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0000000/reference', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 404: ''>},); kwds: {}
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.12/site-packages/imdb/parser/http/__init__.py", line 233, in retrieve_unicode
    response = uopener.open(url)
               ^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404:
2024-12-10 04:06:24,535 CRITICAL [imdbpy] /home/user/.local/lib/python3.12/site-packages/imdb/__init__.py:850: caught an exception retrieving or parsing "main" info set for mopID "0000000" (accessSystem: http)
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.12/site-packages/imdb/parser/http/__init__.py", line 233, in retrieve_unicode
    response = uopener.open(url)
               ^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.12/site-packages/imdb/__init__.py", line 848, in update
    ret = method(mopID)
          ^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/imdb/parser/http/__init__.py", line 481, in get_movie_main
    cont = self._retrieve(self.urls['movie_main'] % movieID + 'reference')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/imdb/parser/http/__init__.py", line 392, in _retrieve
    ret = self.urlOpener.retrieve_unicode(url, size=size)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/imdb/parser/http/__init__.py", line 261, in retrieve_unicode
    raise IMDbDataAccessError(
imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0000000/reference', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 404: ''>}
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.12/site-packages/imdb/parser/http/__init__.py", line 233, in retrieve_unicode
    response = uopener.open(url)
               ^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Upload-Assistant/upload.py", line 983, in <module>
    asyncio.run(do_the_thing(base_dir))  # Pass the correct base_dir value here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.7/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/user/Upload-Assistant/upload.py", line 500, in do_the_thing
    await process_meta(meta, base_dir)
  File "/home/user/Upload-Assistant/upload.py", line 253, in process_meta
    meta = await prep.gather_prep(meta=meta, mode='cli')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Upload-Assistant/src/prep.py", line 678, in gather_prep
    meta = await self.tmdb_other_meta(meta)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Upload-Assistant/src/prep.py", line 1922, in tmdb_other_meta
    meta['aka'], original_language = await self.get_imdb_aka(meta['imdb_id'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Upload-Assistant/src/prep.py", line 3859, in get_imdb_aka
    result = ia.get_movie(imdb_id.replace('tt', ''))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/imdb/__init__.py", line 429, in get_movie
    self.update(movie, info)
  File "/home/user/.local/lib/python3.12/site-packages/imdb/__init__.py", line 848, in update
    ret = method(mopID)
          ^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/imdb/parser/http/__init__.py", line 481, in get_movie_main
    cont = self._retrieve(self.urls['movie_main'] % movieID + 'reference')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/imdb/parser/http/__init__.py", line 392, in _retrieve
    ret = self.urlOpener.retrieve_unicode(url, size=size)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/imdb/parser/http/__init__.py", line 261, in retrieve_unicode
    raise IMDbDataAccessError(
imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0000000/reference', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 404: ''>}

**Comment by deitybob12** [comment]
Thank you. This resolved the issue with this upload. You rock!
