### ISSUE TITLE
Issues after recent update

### ISSUE THREAD

**Issue by nsrafk** [Audionut/Upload-Assistant#19]
Hello good sir

Im using the docker version of your fork. It worked perfectly fine up until today i think. I get the below error no matter what i do:

```
Traceback (most recent call last):
  File "/Upload-Assistant/upload.py", line 582, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Upload-Assistant/upload.py", line 191, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli') 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Upload-Assistant/src/prep.py", line 165, in gather_prep
    video, meta['scene'], meta['imdb'] = self.is_scene(videopath, meta.get('imdb', None))
                                         ^^^^^^^^^^^^^
AttributeError: 'Prep' object has no attribute 'is_scene'
```

Can you help out?

**Comment by nsrafk** [comment]
Im using the master branch.

When i use the developer branch it works again.
