### ISSUE TITLE
PTP must choose a resolution exception on DVD5 even with --resolution set

### ISSUE THREAD

**Issue by BoBeR182** [Audionut/Upload-Assistant#193]
Uploading to PTP there seems to be a bug in the parser.

```
Traceback (most recent call last):
  File "/home/bober/Upload-Assistant/upload.py", line 804, in do_the_thing
    await ptp.upload(meta, ptpUrl, ptpData, disctype)
  File "/home/bober/Upload-Assistant/src/trackers/PTP.py", line 1038, in upload
    raise UploadException(f"Upload to PTP failed: {errorMessage} ({response.status_code}). (We are still on the upload page.)")  # noqa F405
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src.exceptions.UploadException: Upload to PTP failed: <div>You must choose a resolution. (200). (We are still on the upload page.)
```

meta.json contents have resolution set correctly.
```json
{
    "base_dir": "/home/bober/Upload-Assistant",
    "manual_frames": null,
    "path": "/media/Storage/incoming/Movie Name (2021) DVD5 DD2.0",
    "queue": null,
    "unit3d": false,
    "screens": 6,
    "category": "MOVIE",
    "manual_type": "DISC",
    "manual_source": null,
    "resolution": "480p",
    "tmdb_manual": null,
    "imdb": null,
    "mal": null,
    "tvmaze_manual": null,
    "tvdb_manual": null,
    "tag": "",
    "service": "",
    "distributor": "",
    "manual_edition": null,
    "season": null,
    "episode": null,
    "manual_date": null,
    "no_season": false,
    "no_year": false,
    "no_aka": false,
    "no_dub": false,
    "no_tag": false,
    "no_edition": false,
    "dual_audio": false,
    "no_seed": false,
    "manual_year": 0,
    "ptp": null,
    "blu": null,
    "aither": null,
    "lst": null,
    "oe": null,
    "tik": null,
    "hdb": null,
    "foreign": false,
    "opera": false,
    "asian": false,
    "disctype": "NTSC DVD5",
    "untouched": false,
    "desc": null,
    "manual_dvds": "",
    "desclink": null,
    "descfile": null,
    "imghost": "ptpimg",
    "skip_imghost_upload": false,
    "torrenthash": null,
    "nfo": false,
    "keywords": "",
    "keep_folder": false,
    "region": null,
    "anon": 0,
    "stream": 0,
    "webdv": false,
    "hardcoded-subs": false,
    "personalrelease": false,
    "dupe": false,
    "debug": true,
    "ffdebug": false,
    "manual": false,
    "max_piece_size": null,
    "nohash": false,
    "rehash": false,
    "draft": false,
    "modq": false,
    "client": "deluge",
    "qbit_tag": null,
    "qbit_cat": null,
    "rtorrent_label": null,
    "trackers": null,
    "randomized": 0,
    "unattended": false,
    "unattended_confirm": false,
    "vapoursynth": false,
    "cleanup": false,
    "freeleech": 0,
    "infohash": null,
    "uuid": "Movie Name (2021) DVD5 DD2.0",
    "cutoff": 3,
    "mode": "cli",
    "isdir": true,
    "saved_description": false,
    "is_disc": "DVD",
    "discs": [
        {
            "path": "/media/Storage/incoming/Movie Name (2021) DVD5 DD2.0/VIDEO_TS",
            "name": "Movie Name (2021) DVD5 DD2.0",
            "type": "DVD",
            "vob_mi": "General\nComplete name                            : VTS_01_1.VOB\nFormat                                   : MPEG-PS\nFile size                                : 1 024 MiB\nDuration                                 : 34 min 24 s\nOverall bit rate mode                    : Variable\nOverall bit rate                         : 4 160 kb/s\nFrame rate                               : 23.976 FPS\n\nVideo\nID                                       : 224 (0xE0)\nFormat                                   : MPEG Video\nFormat version                           : Version 2\nFormat profile                           : Main@Main\nFormat settings                          : CustomMatrix / BVOP\nFormat settings, BVOP                    : Yes\nFormat settings, Matrix                  : Custom\nFormat settings, GOP                     : M=3, N=12\nDuration                                 : 34 min 24 s\nBit rate mode                            : Variable\nBit rate                                 : 3 885 kb/s\nMaximum bit rate                         : 7 738 kb/s\nWidth                                    : 720 pixels\nHeight                                   : 480 pixels\nDisplay aspect ratio                     : 16:9\nFrame rate                               : 23.976 (24000/1001) FPS\nColor space                              : YUV\nChroma subsampling                       : 4:2:0\nBit depth                                : 8 bits\nScan type                                : Progressive\nScan order                               : 2:3 Pulldown\nCompression mode                         : Lossy\nBits/(Pixel*Frame)                       : 0.469\nTime code of first frame                 : 00:00:00:00\nTime code source                         : Group of pictures header\nGOP, Open/Closed                         : Open\nGOP, Open/Closed of first frame          : Closed\nStream size                              : 956 MiB (93%)\n\nAudio\nID                                       : 189 (0xBD)-128 (0x80)\nFormat                                   : AC-3\nFormat/Info                              : Audio Coding 3\nCommercial name                          : Dolby Digital\nMuxing mode                              : DVD-Video\nDuration                                 : 34 min 24 s\nBit rate mode                            : Constant\nBit rate                                 : 192 kb/s\nChannel(s)                               : 2 channels\nChannel layout                           : L R\nSampling rate                            : 48.0 kHz\nFrame rate                               : 31.250 FPS (1536 SPF)\nCompression mode                         : Lossy\nStream size                              : 47.3 MiB (5%)\nService kind                             : Complete Main\nDialog Normalization                     : -31 dB\ndialnorm_Average                         : -31 dB\ndialnorm_Minimum                         : -31 dB\ndialnorm_Maximum                         : -31 dB\n\nText\nID                                       : 189 (0xBD)-32 (0x20)\nFormat                                   : RLE\nFormat/Info                              : Run-length encoding\nMuxing mode                              : DVD-Video\nDelay relative to video                  : 2 s 370 ms\n\nMenu\nFormat                                   : DVD-Video\n\nReportBy                                 : MediaInfoLib - v24.06\n",
            "ifo_mi": "General\nComplete name                            : VTS_01_0.IFO\nFormat                                   : DVD Video\nFile size                                : 84.0 KiB\nDuration                                 : 2 h 20 min\nOverall bit rate mode                    : Variable\nOverall bit rate                         : 4 160 kb/s\nFrame rate                               : 23.976 FPS\n\nVideo\nID                                       : 224 (0xE0)\nFormat                                   : MPEG Video\nFormat version                           : Version 2\nFormat profile                           : Main@Main\nFormat settings                          : CustomMatrix / BVOP\nFormat settings, BVOP                    : Yes\nFormat settings, Matrix                  : Custom\nFormat settings, GOP                     : M=3, N=12\nDuration                                 : 2 h 20 min\nBit rate mode                            : Variable\nBit rate                                 : 3 885 kb/s\nMaximum bit rate                         : 7 738 kb/s\nWidth                                    : 720 pixels\nHeight                                   : 480 pixels\nDisplay aspect ratio                     : 16:9\nFrame rate                               : 23.976 (24000/1001) FPS\nColor space                              : YUV\nChroma subsampling                       : 4:2:0\nBit depth                                : 8 bits\nScan type                                : Progressive\nScan order                               : 2:3 Pulldown\nCompression mode                         : Lossy\nBits/(Pixel*Frame)                       : 0.469\nTime code of first frame                 : 00:00:00:00\nTime code source                         : Group of pictures header\nGOP, Open/Closed                         : Open\nGOP, Open/Closed of first frame          : Closed\nStream size                              : 956 MiB\nintra_dc_precision                       : 8\n\nAudio\nID                                       : 189 (0xBD)-128 (0x80)\nFormat                                   : AC-3\nFormat/Info                              : Audio Coding 3\nCommercial name                          : Dolby Digital\nMuxing mode                              : DVD-Video\nDuration                                 : 2 h 20 min\nBit rate mode                            : Constant\nBit rate                                 : 192 kb/s\nChannel(s)                               : 2 channels\nChannel layout                           : L R\nSampling rate                            : 48.0 kHz\nFrame rate                               : 31.250 FPS (1536 SPF)\nCompression mode                         : Lossy\nStream size                              : 47.3 MiB\nService kind                             : Complete Main\nbsid                                     : 8\nDialog Normalization                     : -31\nDialog Normalization                     : -31 dB\ndsurmod                                  : 0\nacmod                                    : 2\nlfeon                                    : 0\ndialnorm_Average                         : -31\ndialnorm_Average                         : -31 dB\ndialnorm_Minimum                         : -31\ndialnorm_Minimum                         : -31 dB\ndialnorm_Maximum                         : -31\ndialnorm_Maximum                         : -31 dB\ndialnorm_Count                           : 2\nSamplingCount_Source                     : General_Duration\nDuration_Source                          : General_Duration\n\nText\nID                                       : 189 (0xBD)-32 (0x20)\nFormat                                   : RLE\nFormat/Info                              : Run-length encoding\nMuxing mode                              : DVD-Video\nDuration                                 : 2 h 20 min\nDelay relative to video                  : 2 s 370 ms\n\nMenu\nDuration                                 : 2 h 20 min\n00:00:00.000                             : Chapter 1\n00:05:00.100                             : Chapter 2\n00:09:59.533                             : Chapter 3\n00:14:59.233                             : Chapter 4\n00:19:58.933                             : Chapter 5\n00:24:58.867                             : Chapter 6\n00:29:58.300                             : Chapter 7\n00:34:57.867                             : Chapter 8\n00:39:57.567                             : Chapter 9\n00:44:57.633                             : Chapter 10\n00:49:57.067                             : Chapter 11\n00:54:56.867                             : Chapter 12\n00:59:56.567                             : Chapter 13\n01:04:56.000                             : Chapter 14\n01:09:55.800                             : Chapter 15\n01:14:55.733                             : Chapter 16\n01:19:55.433                             : Chapter 17\n01:24:54.733                             : Chapter 18\n01:29:54.533                             : Chapter 19\n01:34:54.233                             : Chapter 20\n01:39:53.933                             : Chapter 21\n01:44:53.633                             : Chapter 22\n01:49:53.200                             : Chapter 23\n01:54:52.900                             : Chapter 24\n01:59:52.833                             : Chapter 25\n02:04:52.533                             : Chapter 26\n02:09:52.233                             : Chapter 27\n02:14:51.667                             : Chapter 28\n02:19:51.733                             : Chapter 29\nList (Audio)                             : 0\nList (Subtitles 4/3)                     : 0\nList (Subtitles Wide)                    : 0\nList (Subtitles Letterbox)               : 0\nList (Subtitles Pan&Scan)                : 0\n\nReportBy                                 : MediaInfoLib - v24.06\n",
            "main_set": [
                "01_1.VOB",
                "01_2.VOB",
                "01_3.VOB",
                "01_4.VOB",
                "01_5.VOB"
            ],
            "size": "DVD5",
            "vob": "/media/Storage/incoming/Movie Name (2021) DVD5 DD2.0/VIDEO_TS/VTS_01_1.VOB",
            "ifo": "/media/Storage/incoming/Movie Name (2021) DVD5 DD2.0/VIDEO_TS/VTS_01_0.IFO",
            "vob_mi_full": "General\nComplete name                            : /media/Storage/incoming/Movie Name (2021) DVD5 DD2.0/VIDEO_TS/VTS_01_1.VOB\nCompleteName_Last                        : /media/Storage/incoming/Movie Name (2021) DVD5 DD2.0/VIDEO_TS/VTS_01_5.VOB\nFormat                                   : MPEG-PS\nFile size                                : 4.07 GiB\nDuration                                 : 2 h 20 min\nOverall bit rate mode                    : Variable\nOverall bit rate                         : 4 157 kb/s\nFrame rate                               : 23.976 FPS\n\nVideo\nID                                       : 224 (0xE0)\nFormat                                   : MPEG Video\nFormat version                           : Version 2\nFormat profile                           : Main@Main\nFormat settings                          : CustomMatrix / BVOP\nFormat settings, BVOP                    : Yes\nFormat settings, Matrix                  : Custom\nFormat settings, GOP                     : M=3, N=12\nDuration                                 : 2 h 20 min\nBit rate mode                            : Variable\nBit rate                                 : 3 882 kb/s\nMaximum bit rate                         : 7 738 kb/s\nWidth                                    : 720 pixels\nHeight                                   : 480 pixels\nDisplay aspect ratio                     : 16:9\nFrame rate                               : 23.976 (24000/1001) FPS\nColor space                              : YUV\nChroma subsampling                       : 4:2:0\nBit depth                                : 8 bits\nScan type                                : Progressive\nScan order                               : 2:3 Pulldown\nCompression mode                         : Lossy\nBits/(Pixel*Frame)                       : 0.469\nTime code of first frame                 : 00:00:00:00\nTime code source                         : Group of pictures header\nGOP, Open/Closed                         : Open\nGOP, Open/Closed of first frame          : Closed\nStream size                              : 3.80 GiB (93%)\n\nAudio\nID                                       : 189 (0xBD)-128 (0x80)\nFormat                                   : AC-3\nFormat/Info                              : Audio Coding 3\nCommercial name                          : Dolby Digital\nMuxing mode                              : DVD-Video\nDuration                                 : 2 h 20 min\nBit rate mode                            : Constant\nBit rate                                 : 192 kb/s\nChannel(s)                               : 2 channels\nChannel layout                           : L R\nSampling rate                            : 48.0 kHz\nFrame rate                               : 31.250 FPS (1536 SPF)\nCompression mode                         : Lossy\nStream size                              : 192 MiB (5%)\nService kind                             : Complete Main\nDialog Normalization                     : -31 dB\ndialnorm_Average                         : -31 dB\ndialnorm_Minimum                         : -31 dB\ndialnorm_Maximum                         : -31 dB\n\nText\nID                                       : 189 (0xBD)-32 (0x20)\nFormat                                   : RLE\nFormat/Info                              : Run-length encoding\nMuxing mode                              : DVD-Video\nDelay relative to video                  : 2 s 370 ms\n\nMenu\nFormat                                   : DVD-Video\n\nReportBy                                 : MediaInfoLib - v24.06\n",
            "ifo_mi_full": "General\nComplete name                            : /media/Storage/incoming/Movie Name (2021) DVD5 DD2.0/VIDEO_TS/VTS_01_0.IFO\nFormat                                   : DVD Video\nFile size                                : 4.07 GiB\nDuration                                 : 2 h 20 min\nOverall bit rate mode                    : Variable\nOverall bit rate                         : 4 157 kb/s\nFrame rate                               : 23.976 FPS\n\nVideo\nID                                       : 224 (0xE0)\nFormat                                   : MPEG Video\nFormat version                           : Version 2\nFormat profile                           : Main@Main\nFormat settings                          : CustomMatrix / BVOP\nFormat settings, BVOP                    : Yes\nFormat settings, Matrix                  : Custom\nFormat settings, GOP                     : M=3, N=12\nDuration                                 : 2 h 20 min\nBit rate mode                            : Variable\nBit rate                                 : 3 882 kb/s\nMaximum bit rate                         : 7 738 kb/s\nWidth                                    : 720 pixels\nHeight                                   : 480 pixels\nDisplay aspect ratio                     : 16:9\nFrame rate                               : 23.976 (24000/1001) FPS\nColor space                              : YUV\nChroma subsampling                       : 4:2:0\nBit depth                                : 8 bits\nScan type                                : Progressive\nScan order                               : 2:3 Pulldown\nCompression mode                         : Lossy\nBits/(Pixel*Frame)                       : 0.469\nTime code of first frame                 : 00:00:00:00\nTime code source                         : Group of pictures header\nGOP, Open/Closed                         : Open\nGOP, Open/Closed of first frame          : Closed\nStream size                              : 3.80 GiB (93%)\nintra_dc_precision                       : 8\nSource                                   : VTS_01_1.VOB\n\nAudio\nID                                       : 189 (0xBD)-128 (0x80)\nFormat                                   : AC-3\nFormat/Info                              : Audio Coding 3\nCommercial name                          : Dolby Digital\nMuxing mode                              : DVD-Video\nDuration                                 : 2 h 20 min\nBit rate mode                            : Constant\nBit rate                                 : 192 kb/s\nChannel(s)                               : 2 channels\nChannel layout                           : L R\nSampling rate                            : 48.0 kHz\nFrame rate                               : 31.250 FPS (1536 SPF)\nCompression mode                         : Lossy\nStream size                              : 192 MiB (5%)\nService kind                             : Complete Main\nbsid                                     : 8\nDialog Normalization                     : -31\nDialog Normalization                     : -31 dB\ndsurmod                                  : 0\nacmod                                    : 2\nlfeon                                    : 0\ndialnorm_Average                         : -31\ndialnorm_Average                         : -31 dB\ndialnorm_Minimum                         : -31\ndialnorm_Minimum                         : -31 dB\ndialnorm_Maximum                         : -31\ndialnorm_Maximum                         : -31 dB\ndialnorm_Count                           : 2\nSamplingCount_Source                     : General_Duration\nDuration_Source                          : General_Duration\nSource                                   : VTS_01_1.VOB\n\nText\nID                                       : 189 (0xBD)-32 (0x20)\nFormat                                   : RLE\nFormat/Info                              : Run-length encoding\nMuxing mode                              : DVD-Video\nDuration                                 : 2 h 20 min\nDelay relative to video                  : 2 s 370 ms\nSource                                   : VTS_01_1.VOB\n\nMenu\nDuration                                 : 2 h 20 min\n00:00:00.000                             : Chapter 1\n00:05:00.100                             : Chapter 2\n00:09:59.533                             : Chapter 3\n00:14:59.233                             : Chapter 4\n00:19:58.933                             : Chapter 5\n00:24:58.867                             : Chapter 6\n00:29:58.300                             : Chapter 7\n00:34:57.867                             : Chapter 8\n00:39:57.567                             : Chapter 9\n00:44:57.633                             : Chapter 10\n00:49:57.067                             : Chapter 11\n00:54:56.867                             : Chapter 12\n00:59:56.567                             : Chapter 13\n01:04:56.000                             : Chapter 14\n01:09:55.800                             : Chapter 15\n01:14:55.733                             : Chapter 16\n01:19:55.433                             : Chapter 17\n01:24:54.733                             : Chapter 18\n01:29:54.533                             : Chapter 19\n01:34:54.233                             : Chapter 20\n01:39:53.933                             : Chapter 21\n01:44:53.633                             : Chapter 22\n01:49:53.200                             : Chapter 23\n01:54:52.900                             : Chapter 24\n01:59:52.833                             : Chapter 25\n02:04:52.533                             : Chapter 26\n02:09:52.233                             : Chapter 27\n02:14:51.667                             : Chapter 28\n02:19:51.733                             : Chapter 29\nList (Audio)                             : 0\nList (Subtitles 4/3)                     : 0\nList (Subtitles Wide)                    : 0\nList (Subtitles Letterbox)               : 0\nList (Subtitles Pan&Scan)                : 0\nSource                                   : VTS_01_1.VOB\n\nReportBy                                 : MediaInfoLib - v24.06\n"
        }
    ],
    "scene": false,
    "filelist": [],
    "search_year": 2021,
    "mediainfo": {
        "creatingLibrary": {
            "name": "MediaInfoLib",
            "version": "24.06",
            "url": "https://mediaarea.net/MediaInfo"
        },
        "media": {
            "@ref": "/media/Storage/incoming/Movie Name (2021) DVD5 DD2.0/VIDEO_TS/VTS_01_1.VOB",
            "track": [
                {
                    "@type": "General",
                    "UniqueID": {},
                    "VideoCount": "1",
                    "AudioCount": "1",
                    "TextCount": "1",
                    "MenuCount": "1",
                    "FileExtension": "VOB",
                    "Format": "MPEG-PS",
                    "Format_Version": {},
                    "FileSize": "4370122752",
                    "Duration": "8410.217",
                    "OverallBitRate": "4156966",
                    "FrameRate": "23.976",
                    "FrameCount": "201643",
                    "StreamSize": "86972283",
                    "IsStreamable": {},
                    "File_Created_Date": {},
                    "File_Created_Date_Local": {},
                    "File_Modified_Date": "2024-12-11 14:20:28 UTC",
                    "File_Modified_Date_Local": "2024-12-11 09:20:28",
                    "Encoded_Application": {},
                    "Encoded_Library": {}
                },
                {
                    "@type": "Video",
                    "StreamOrder": {},
                    "ID": "224",
                    "UniqueID": {},
                    "Format": "MPEG Video",
                    "Format_Profile": "Main",
                    "Format_Version": "2",
                    "Format_Level": "Main",
                    "Format_Tier": {},
                    "HDR_Format": {},
                    "HDR_Format_Version": {},
                    "HDR_Format_String": {},
                    "HDR_Format_Profile": {},
                    "HDR_Format_Level": {},
                    "HDR_Format_Settings": {},
                    "HDR_Format_Compression": {},
                    "HDR_Format_Compatibility": {},
                    "CodecID": {},
                    "CodecID_Hint": {},
                    "Duration": "8410.217",
                    "BitRate": "3882242",
                    "Width": "720",
                    "Height": "480",
                    "Stored_Height": {},
                    "Sampled_Width": "720",
                    "Sampled_Height": "480",
                    "PixelAspectRatio": "1.185",
                    "DisplayAspectRatio": "1.778",
                    "FrameRate_Mode": {},
                    "FrameRate": "23.976",
                    "FrameRate_Num": "24000",
                    "FrameRate_Den": "1001",
                    "FrameCount": "201643",
                    "Standard": {},
                    "ColorSpace": "YUV",
                    "ChromaSubsampling": "4:2:0",
                    "ChromaSubsampling_Position": {},
                    "BitDepth": "8",
                    "ScanType": "Progressive",
                    "ScanOrder": "2:3 Pulldown",
                    "Delay": "0.288933333",
                    "Delay_Source": "Container",
                    "StreamSize": "4081305261",
                    "Language": {},
                    "Default": {},
                    "Forced": {},
                    "colour_description_present": {},
                    "colour_description_present_Source": {},
                    "colour_range": {},
                    "colour_range_Source": {},
                    "colour_primaries": {},
                    "colour_primaries_Source": {},
                    "transfer_characteristics": {},
                    "transfer_characteristics_Source": {},
                    "transfer_characteristics_Original": {},
                    "matrix_coefficients": {},
                    "matrix_coefficients_Source": {},
                    "MasteringDisplay_ColorPrimaries": {},
                    "MasteringDisplay_ColorPrimaries_Source": {},
                    "MasteringDisplay_Luminance": {},
                    "MasteringDisplay_Luminance_Source": {},
                    "MaxCLL": {},
                    "MaxCLL_Source": {},
                    "MaxFALL": {},
                    "MaxFALL_Source": {},
                    "Encoded_Library_Settings": {}
                },
                {
                    "@type": "Audio",
                    "StreamOrder": "0",
                    "ID": "189-128",
                    "UniqueID": {},
                    "Format": "AC-3",
                    "Format_Commercial_IfAny": "Dolby Digital",
                    "Format_Settings_Endianness": "Big",
                    "Format_AdditionalFeatures": {},
                    "CodecID": {},
                    "Duration": "8410.217",
                    "BitRate_Mode": "CBR",
                    "BitRate": "192000",
                    "Channels": "2",
                    "ChannelPositions": "Front: L R",
                    "ChannelLayout": "L R",
                    "Channels_Original": {},
                    "ChannelLayout_Original": {},
                    "SamplesPerFrame": "1536",
                    "SamplingRate": "48000",
                    "SamplingCount": "403690416",
                    "FrameRate": "31.250",
                    "FrameCount": {},
                    "Compression_Mode": "Lossy",
                    "Delay": "0.288933333",
                    "Delay_Source": "Container",
                    "Video_Delay": "0.000",
                    "StreamSize": "201845208",
                    "Title": {},
                    "Language": {},
                    "ServiceKind": "CM",
                    "Default": {},
                    "Forced": {},
                    "extra": {
                        "bsid": "8",
                        "dialnorm": "-31",
                        "dialnorm_String": "-31 dB",
                        "dsurmod": "0",
                        "acmod": "2",
                        "lfeon": "0",
                        "dialnorm_Average": "-31",
                        "dialnorm_Average_String": "-31 dB",
                        "dialnorm_Minimum": "-31",
                        "dialnorm_Minimum_String": "-31 dB",
                        "dialnorm_Maximum": "-31",
                        "dialnorm_Maximum_String": "-31 dB",
                        "dialnorm_Count": "2",
                        "SamplingCount_Source": "General_Duration",
                        "Duration_Source": "General_Duration"
                    }
                },
                {
                    "@type": "Text",
                    "@typeorder": {},
                    "StreamOrder": "0",
                    "ID": "189-32",
                    "UniqueID": {},
                    "Format": "RLE",
                    "CodecID": {},
                    "Duration": {},
                    "BitRate": {},
                    "FrameRate": {},
                    "FrameCount": {},
                    "ElementCount": {},
                    "StreamSize": {},
                    "Title": {},
                    "Language": {},
                    "Default": {},
                    "Forced": {}
                },
                {
                    "@type": "Menu",
                    "extra": {}
                }
            ]
        }
    },
    "dvd_size": "DVD5",
    "sd": 1,
    "filename": "Movie Name",
    "bdinfo": null,
    "description": "",
    "ext_torrenthash": null,
    "tvdb_id": 0,
    "hdb_name": null,
    "tmdb": "XXXXXXX",
    "type": "DISC",
    "title": "Movie Name",
    "year": 2020,
    "imdb_id": "XXXXXXXXX",
    "youtube": "XXXXXXXXX",
    "aka": "",
    "original_language": "en",
    "original_title": "Movie Name",
    "genres": "Horror, Fantasy, Mystery",
    "tmdb_directors": [],
    "mal_id": 0,
    "anime": false,
    "poster": "XXXXXXXXXXX",
    "tmdb_poster": "XXXXXXXX",
    "overview": "XXXXXXXXXXX.",
    "tmdb_type": "Movie",
    "runtime": 60,
    "tvmaze_id": 0,
    "imdb_info": {
        "title": "Movie Name",
        "year": 2020,
        "aka": "Movie Name",
        "type": "movie",
        "imdbID": "XXXXXXXXX",
        "runtime": "140",
        "cover": "XXXXXXXX",
        "plot": "XXXXXXXXXX.",
        "genres": "Horror, Mystery",
        "rating": 4.1,
        "original_language": null,
        "directors": [
            "XXXX",
            "XXXX"
        ]
    },
    "video": "/media/Storage/incoming/Movie Name (2021) DVD5 DD2.0",
    "audio": "DD 2.0",
    "channels": "2.0",
    "has_commentary": false,
    "3D": "",
    "source": "",
    "service_longname": "",
    "uhd": "",
    "hdr": "",
    "video_encode": " ",
    "video_codec": "MPEG-2",
    "has_encode_settings": false,
    "bit_depth": "8",
    "edition": "",
    "repack": "",
    "name_notag": "Movie Name 2020 DVD5 DD 2.0",
    "name": "Movie Name 2020 DVD5 DD 2.0",
    "clean_name": "Movie Name 2020 DVD5 DD 2.0",
    "potential_missing": [
        "edition",
        "distributor"
    ],
    "edit": true
}
```

but when running with --debug and looking at what is sent to PTP page resolution is dropped

```json
{
   "submit":"true",
   "remaster_year":"",
   "remaster_title":"",
   "type":"Feature Film",
   "codec":"Other",
   "other_codec":"DVD5",
   "container":"Other",
   "other_container":"VOB IFO",
   "resolution":"",
   "source":"Other",
   "other_source":"OtherR",
   "release_desc":"XXXXXXXXXXXXXXXXXX",
   "nfo_text":"",
   "subtitles[]":[
      44
   ],
   "trumpable[]":[
      14
   ],
   "AntiCsrfToken":"XXXXX",
   "imdb":"XXXXX",
   "groupid":"XXXXX"
}
```

**Comment by Audionut** [comment]
With DVD, the resolution should be something like `'resolution': 'NTSC',`
You're seeing the empty resolution being sent because the code is stripping DVD from source
https://github.com/Audionut/Upload-Assistant/blob/e7be8c7a53829b3fd1b8ed28b9438ee83039fdb7/src/trackers/PTP.py#L444
but there's no remaining NTSC or PAL.

There's no NTSC or PAL because `"Standard": {},` from mediainfo is blank, and because it can't be guessed from the filename
https://github.com/Audionut/Upload-Assistant/blob/e7be8c7a53829b3fd1b8ed28b9438ee83039fdb7/src/prep.py#L2469
because it's not in the filename either.

There's not a super simple solution to this, let me think about it.

**Comment by BoBeR182** [comment]
Can we just add NTSC and PAL to the resolution list, I tried `--resolution NTSC` and was blocked by the arg value filter on https://github.com/Audionut/Upload-Assistant/blob/master/src/args.py#L31

**Comment by Audionut** [comment]
No. The existing code is coded based on the set existing values. Just adding XX is most likely to cause issues with other code.

Maybe it won't cause issues, but it likely will. As I mentioned, I just need time to think of the best solution.

**Comment by swannie-eire** [comment]
Would a possible option to get resolution from the screenshots

**Comment by Audionut** [comment]
> There's no NTSC or PAL (in the resolution sent to PTP) because "Standard": {}, from mediainfo is blank, and because it can't be guessed from the filename because it's not in the filename either.
