### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by AN1MATEK** [Audionut/Upload-Assistant#20]
Hello,

Today I started receiving this error or a similar one on some uploads. It seems related to the audio channels. 
```
Traceback (most recent call last):
  File "/Upload-Assistant/upload.py", line 582, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Upload-Assistant/upload.py", line 191, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Upload-Assistant/src/prep.py", line 342, in gather_prep
    meta['audio'], meta['channels'], meta['has_commentary'] = self.get_audio_v2(mi, meta, bdinfo)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Upload-Assistant/src/prep.py", line 1609, in get_audio_v2
    if "LFE" in channel_layout:
       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

```
mediainfo: https://pastebin.com/YEeLxG17

**Comment by AN1MATEK** [comment]
Another example
```
Traceback (most recent call last):
  File "/Upload-Assistant/upload.py", line 582, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Upload-Assistant/upload.py", line 191, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Upload-Assistant/src/prep.py", line 342, in gather_prep
    meta['audio'], meta['channels'], meta['has_commentary'] = self.get_audio_v2(mi, meta, bdinfo)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Upload-Assistant/src/prep.py", line 1730, in get_audio_v2
    if additional.endswith("X"):
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'
```
mediainfo: https://pastebin.com/c5kmbaZT

I also want to point out that these files where uploaded in the past without an issue. It seems some recent change broke it.

**Comment by Audionut** [comment]
Ah thanks. I seen that error myself, but lost it whilst trying to do other things. Can you please pull an update and confirm the fix works.

**Comment by AN1MATEK** [comment]
I pulled master and develop but neither worked. I am using Docker though, so it may not be there yet.

**Comment by Audionut** [comment]
I think I know where the real issue is, I'm just waiting on a download of a file known to cause the error before attempting any further.

**Comment by Audionut** [comment]
That fixed worked here @AN1MATEK can you confirm you are running the latest master branch.

**Comment by AN1MATEK** [comment]
Yes, it seems that I am using the correct version, but unfortunately it does not work.
```
root@unraid:~# docker pull ghcr.io/audionut/upload-assistant:master
master: Pulling from audionut/upload-assistant
903681d87777: Already exists
3cbbe86a28c2: Already exists
6ed93aa58a52: Already exists
787c78da4383: Already exists
00683c1a0086: Already exists
86eeafd0d69e: Already exists
08f524b85948: Already exists
8a9626274869: Already exists
3d8483dcb399: Already exists
522b556668a1: Already exists
abc3b7de8650: Already exists
7560c45e7cc1: Already exists
a64332ce6f4f: Already exists
6442307a6c52: Already exists
725aeb8932f4: Pull complete
Digest: sha256:daf84e6b950e077548b8a846bb12623513f8b8014accd27f60e1748ca34b4485
Status: Downloaded newer image for ghcr.io/audionut/upload-assistant:master
ghcr.io/audionut/upload-assistant:master
root@unraid:~# upload-assistant movies/David.Gilmour.Live.At.Pompeii.2017.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-Destiny.mkv
Gathering info for David.Gilmour.Live.At.Pompeii.2017.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-Destiny.mkv
Reusing screenshots
Traceback (most recent call last):
  File "/Upload-Assistant/upload.py", line 582, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Upload-Assistant/upload.py", line 191, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Upload-Assistant/src/prep.py", line 342, in gather_prep
    meta['audio'], meta['channels'], meta['has_commentary'] = self.get_audio_v2(mi, meta, bdinfo)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Upload-Assistant/src/prep.py", line 1732, in get_audio_v2
    if additional.endswith("X"):
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'
```

Just for reference:
`alias upload-assistant="docker run --rm -it --name='upload-assistant' --net='host' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e HOST_HOSTNAME="unraid" -e HOST_CONTAINERNAME="upload-assistant" -e 'PGID'='100' -e 'PUID'='99' -e '022'='022' -l net.unraid.docker.managed=dockerman -v '/mnt/user/appdata/upload-assistant/data/config.py':'/Upload-Assistant/data/config.py':'rw' -v '/mnt/user/media/torrents/':'/media/torrents/':'rw' -v '/mnt/user/appdata/qbt/config/qBittorrent/BT_backup/':'/BT_backup':'ro' -v '/mnt/user/appdata/upload-assistant/tmp/':'/Upload-Assistant/tmp/':'rw' -w '/media/torrents/' 'ghcr.io/audionut/upload-assistant:master'"`

I really appreciate your help.

**Comment by Audionut** [comment]
I've run out of time to check locally, but the latest update should account for all cases within that function. I'll have to double check other functions later.

**Comment by AN1MATEK** [comment]
I just completely deleted all the images from `upload-assistant` and did a full redownload from `master` but still facing the issue with `David.Gilmour.Live.At.Pompeii.2017.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-Destiny.mkv`
