### ISSUE TITLE
AttributeError while picking trackers

### ISSUE THREAD

**Issue by backstab5983** [Audionut/Upload-Assistant#225]
Updated to 3.0.3 using latest docker image and getting this error while uploading:

```
Correct? [y/N]: y
Searching for existing torrents on BLU...
Tracker 'BLU' passed all checks.
Enter 'y' to upload, or press enter to skip uploading:y
Searching for existing torrents on Aither...
Tracker 'AITHER' passed all checks.
Enter 'y' to upload, or press enter to skip uploading:y
Searching for existing torrents on LST...
Tracker 'LST' passed all checks.
Enter 'y' to upload, or press enter to skip uploading:y
Only TV Is allowed at NBL
Searching for existing torrents on ANT...
Traceback (most recent call last):
  File "/Upload-Assistant/upload.py", line 231, in <module>
    asyncio.run(do_the_thing(base_dir))  # Pass the correct base_dir value here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Upload-Assistant/upload.py", line 201, in do_the_thing
    await process_meta(meta, base_dir)
  File "/Upload-Assistant/upload.py", line 82, in process_meta
    meta = await prep.gather_prep(meta=meta, mode='cli')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Upload-Assistant/src/prep.py", line 374, in gather_prep
    meta = await self.gather_prep(meta=meta, mode='cli')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Upload-Assistant/src/prep.py", line 380, in gather_prep
    successful_trackers = await process_all_trackers(meta)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Upload-Assistant/src/trackerstatus.py", line 134, in process_all_trackers
    tracker_name, status = await process_single_tracker(tracker_name, meta)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Upload-Assistant/src/trackerstatus.py", line 67, in process_single_tracker
    dupes = await common.filter_dupes(dupes, local_meta, tracker_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Upload-Assistant/src/trackers/COMMON.py", line 762, in filter_dupes
    if not await process_exclusion(each):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Upload-Assistant/src/trackers/COMMON.py", line 710, in process_exclusion
    if is_dvd or target_source.includes("DVD"):
                 ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'includes'
```

**Comment by Audionut** [comment]
Ah, I forgot to push a fix for this
