### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by strdtyfrudu** [Audionut/Upload-Assistant#31]
:: Correct? (y/N)
> y
:: Upload to AITHER?  (y/N)
> y
Uploading to AITHER
Searching for existing torrents on site...
No dupes found
Traceback (most recent call last):
  File "/home/lskdnfpeo/Upload-Assistant/upload.py", line 591, in <module>
    asyncio.run(do_the_thing(base_dir))
  File "/home/lskdnfpeo/.pyenv/versions/3.12.5/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/lskdnfpeo/.pyenv/versions/3.12.5/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lskdnfpeo/.pyenv/versions/3.12.5/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/lskdnfpeo/Upload-Assistant/upload.py", line 283, in do_the_thing
    await tracker_class.upload(meta)
  File "/home/lskdnfpeo/Upload-Assistant/src/trackers/AITHER.py", line 40, in upload
    name = await self.edit_name(meta)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lskdnfpeo/Upload-Assistant/src/trackers/AITHER.py", line 114, in edit_name
    if track.get('Language', 'None').startswith('en'):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'

I have no clue about this, got it trying to upload a dvd disc aand pulling data from blu

**Comment by Audionut** [comment]
Can you try the fix in the pull request, the file is https://github.com/Audionut/Upload-Assistant/blob/aither-subs-string/src/trackers/AITHER.py

If that doesn't work, can you shoot me a PM either here or at Aither with the DVD so that I can better test locally.

Fairly certain the only argument I ever use is --debug, I'll have a look at those when I get some time. Thanks.
