### ISSUE TITLE
Error using info extracted from BLU

### ISSUE THREAD

**Issue by xmoforf** [Audionut/Upload-Assistant#81]
Getting this error when saying "yes" to using the IDs from the tracker ___.

```
xmoforf@xmoforf:~$ ua stuff.mkv
Running upload-assistant.
Gathering info for stuff.mkv
Exporting MediaInfo...                                                                                                                    MediaInfo Exported.
No ID found in meta for XXX, searching by file name
SearchinFound the following IDs on stuff.mkv
TMDb ID: XXXXX
IMDb ID: https://www.imdb.com/title/ttXXXXXX
Filename: stuff.mkv
Do you want to use these IDs from Tracker? (Y/n): y
Successfully grabbed description from XXX
Extracted description: [code]This release is sourced from Amazon[/code]
Do you want to edit, discard or keep the description?
Enter 'e' to edit, 'd' to discard, or press Enter to keep it as is:
Keeping the original description.
Valid data found on BLU, setting meta values
Image verified successfully: https://ptpimg.me/xxxxxxx.png
Image verified successfully: https://ptpimg.me/xxxxxxx.png
Image verified successfully: https://ptpimg.me/xxxxxxx.png
Image verified successfully: https://ptpimg.me/xxxxxxx.png
Image verified successfully: https://ptpimg.me/xxxxxxx.png
Image verified successfully: https://ptpimg.me/xxxxxxx.png
Traceback (most recent call last):
  File "/home/xmoforf/utilities/audionut-upload-assistant/upload.py", line 621, in <module>
    asyncio.run(do_the_thing(base_dir))  # Pass the correct base_dir value here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmoforf/.pyenv/versions/3.12.0/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/xmoforf/.pyenv/versions/3.12.0/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmoforf/.pyenv/versions/3.12.0/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/xmoforf/utilities/audionut-upload-assistant/upload.py", line 178, in do_the_thing
    meta = await prep.gather_prep(meta=meta, mode='cli')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmoforf/utilities/audionut-upload-assistant/src/prep.py", line 545, in gather_prep
    meta, match = await self.update_metadata_from_tracker('BLU', blu, meta, search_term, search_file_folder)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmoforf/utilities/audionut-upload-assistant/src/prep.py", line 213, in update_metadata_from_tracker
    await self.update_meta_with_unit3d_data(meta, tracker_data, tracker_name)
  File "/home/xmoforf/utilities/audionut-upload-assistant/src/prep.py", line 174, in update_meta_with_unit3d_data
    valid_images = await self.check_images_concurrently(imagelist, meta)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmoforf/utilities/audionut-upload-assistant/src/prep.py", line 122, in check_images_concurrently
    if 'MTV' in trackers_list or 'MTV' in meta.get('trackers', []):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by Audionut** [comment]
https://github.com/Audionut/Upload-Assistant/issues/68

**Comment by xmoforf** [comment]
interesting--i was using master branch. it looks like #68 was fixed a week ago, so this would have been after that was merged I think.

**Comment by xmoforf** [comment]
Yes, in fact the error is happening from the new line of code that was moved to L122, whereas before the commit it was at L308 in prep.py.

**Comment by Audionut** [comment]
And a check was added to convert any strings into a list. Look at the code starting here:
https://github.com/Audionut/Upload-Assistant/blob/69911e59e51ad9933feebc268b51b37adad8c688/src/prep.py#L129

It starts at line 129. Line 122 is a comment `# Run image verification concurrently`, and none of that code contains the line that it giving you your error `if 'MTV' in trackers_list or 'MTV' in meta.get('trackers', []):`

Not sure what on earth is happening, but suggest to nuke everything except (and maybe even) your config.py file and start fresh.

**Comment by xmoforf** [comment]
This is probably a dirty hack, but this seems to fix it.  The problem is that 'trackers' is explicitly being set to None.

```diff
diff --git a/src/prep.py b/src/prep.py
index 0b68d33..cb1f553 100644
--- a/src/prep.py
+++ b/src/prep.py
@@ -135,6 +135,12 @@ class Prep():
             meta['trackers'] = [tracker.strip() for tracker in meta['trackers'].split(',')]

         # Issue warning if any valid image is on an unapproved host and MTV is in the trackers list
+        if meta.get('trackers', []) == None:
+            meta['trackers'] = []
         if 'MTV' in trackers_list or 'MTV' in meta.get('trackers', []):
             if invalid_host_found:
                 console.print("[yellow]Warning: Some images are not hosted on an MTV-approved image host. MTV will fail if you keep these images.[/yellow]")
```

**Comment by Audionut** [comment]
` meta['trackers']` is used extensively. Explicitly setting that is indeed a dirty hack,

Better to find out why your setup is still returning a string when everything is being checked and converted to a list before used.

``` python
        # Collect valid images
        valid_images = [image for image in results if image is not None]

        # Convert default_trackers string into a list
        default_trackers = self.config['TRACKERS'].get('default_trackers', '')
        console.print(f"Blank copy of default_trackers: {default_trackers}")
        trackers_list = [tracker.strip() for tracker in default_trackers.split(',')]
        console.print(f"Split list of default_trackers: {trackers_list}")
        console.print(f"Trackers in the meta: {meta['trackers']}")

        # Ensure meta['trackers'] is a list
        if isinstance(meta.get('trackers', ''), str):
            meta['trackers'] = [tracker.strip() for tracker in meta['trackers'].split()]

        # Issue warning if any valid image is on an unapproved host and MTV is in the trackers list
        if 'MTV' in trackers_list or 'MTV' in meta.get('trackers', []):
            if invalid_host_found:
                console.print("[yellow]Warning: Some images are not hosted on an MTV-approved image host. MTV will fail if you keep these images.[/yellow]")
```

**Comment by xmoforf** [comment]
`meta` comes into `check_images_concurrently` as a dictionary with meta['trackers'] set to "None". So, when it gets to the `isinstance(meta.get('trackers',''), str)` line, it does not do any conversion because "None" != str. Then, in the 'MTV' check, again it returns "None" which is not iterable, hence the error.  The dirty fix is just replacing that None with a []. It would also work to delete meta['trackers'] so that the get() fallthrough works.  I am not sure what to expect meta['trackers'] to be, but this part of the code seems to want it to be a list or to not exist. If it is getting set to None somewhere, it would cause this error.

**Comment by Audionut** [comment]
Did you intentionally leave out you default trackers list?

``` python
Trackers in the meta: None
Warning: Some images are not hosted on an MTV-approved image host. MTV will fail if you keep these images.
```

**Comment by Audionut** [comment]
I was lulling myself into false confidence, since I had MTV in the default_trackers list, and hence was passing the left side without hitting the problematic right side.
